### ISSUE TITLE
stegano-lsb reveal fails with file

### ISSUE THREAD

**Issue by gacallea** [cedricbonhomme/Stegano#18]
I'm trying this example https://stegano.readthedocs.io/en/latest/software/#hide-and-reveal-a-binary-file before I actually move on to "business", but reveal always fails:

```$ wget http://www.gnu.org/music/free-software-song.ogg
--2018-01-25 22:56:05--  http://www.gnu.org/music/free-software-song.ogg
...
free-software-song.ogg                                      100%
...

$ stegano-lsb hide -i v-desktop.jpg -f ./free-software-song.ogg -o ./v2.jpg
$ rm free-software-song.ogg
remove free-software-song.ogg? y
$ stegano-lsb reveal -i v2.jpg -o fsfsong.ogg
Traceback (most recent call last):
  File "/usr/local/bin/stegano-lsb", line 94, in <module>
    data = tools.base642binary(secret)
  File "/usr/local/lib/python3.6/site-packages/stegano/tools.py", line 100, in base642binary
    b64_fname += '==='
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

Am I doing something wrong? is it because of JPG?

**Comment by cedricbonhomme** [comment]
Indeed, LSB steganograpy is much more complex with JPEG. One of the main problem is image compression...
You should try to first convert your image to PNG. Sometimes libraries do this automatically.
