### ISSUE TITLE
Incorrect padding size in `base642string`

### ISSUE THREAD

**Issue by nejdetckenobi** [cedricbonhomme/Stegano#6]
I ran the program to reveal a hidden binary file from my image.
It gave me that error

```
Traceback (most recent call last):
  File "/usr/local/bin/lsb", line 81, in <module>
    data = tools.base642binary(secret)
  File "/usr/local/lib/python3.4/dist-packages/stegano/tools.py", line 110, in base642binary
    return base64.b64decode(b64_fname)
  File "/usr/lib/python3.4/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
Maybe you can add a static padding `===` to the data instead of dynamically calculated padding? That will fix the issue. I'll send you a PR about it.

**Comment by cedricbonhomme** [comment]
Thank you for the issue and the PR! This is I think related to a bug that I already saw one time...
